language: bash

notifications:
    email: false

sudo: required

services:
    - docker

before_install:
    - sudo apt-get install maven maven2

script:
    - install: travis_wait 120 mvn install
    - bash run.sh
